name: Test Report
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
    - uses: dorny/test-reporter@v1.6.0
      with:
        artifact: dotnet-results-${{ matrix.dotnet-version }}
        name: xUnit Tests
        path: '*.trx'
        reporter: dotnet-trx